version: "1.0"
info:
  model: int-scaffold
packages:
- name: JC_TESTProject
  gitServerName: John Carter
  gitUrl: https://github.com/johnpcarter/JC_TESTProject
  gitUsername: johnpcarter
  gitBranch: main
services:
- serviceName: project.jc_test.integrations:random
  packages:
  - name: JC_TESTProject
    version: "1.0"
- serviceName: pub.math:randomDouble
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.jc_test.integrations:log
  packages:
  - name: JC_TESTProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.1018
- serviceName: project.jc_test.integrations:helloWorld
  packages:
  - name: JC_TESTProject
    version: "1.0"
