version: "1.0"
info:
  model: int-scaffold
packages:
- name: JC_TESTProject
  gitServerName: JC_TEST
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
services:
- serviceName: project.jc_test.integrations:helloWorld
  packages:
  - name: JC_TESTProject
    version: "1.0"
